### ISSUE TITLE
LMAO

### ISSUE THREAD

**Issue by cryptobender69** [LeWestopher/Order-Matching-Engine#1]
Hello, This is not how open source works. You need to put some code in the repo for others to come and contribute and grow your project.

**Comment by LeWestopher** [comment]
Congratulations dumbass, you just wasted three minutes of your life commenting on an empty repo with zero stars and zero forks.  I'm not sure what your intention behind this was, but instead of wasting people's lives trolling Github with pointless bullshit, take your own advice and actually write some code, like real OSS contributors do.

Locking this, as OP is obviously a total waste of space.
